(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whatsinourclassicturkeydinner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgDABIgBAAIgBgCQgDgBgDgHQgCgFABgGIAAgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAADAGIADAEQACAEAEACQAEABADAAQAGAAACgCQADgDAAgEQAAgHgLgFIgEgDQgMgGgEgEQgFgEAAgIQAAgKAHgGQAHgHALAAIAFABIAFABIAEgCIACAAQAEAAADAGQADAGAAAGIgBAFQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgDgGQgDgEgEgCQgCgCgFAAQgDAAgDADQgCACgBAEQAAAEAEACQACADAJAFIAAABQAWAJgBAMQAAALgIAHQgHAHgNAAg");
	this.shape.setTransform(132.9,-10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDADgCIADgBQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgJIAAgFIAAgFIAAgFIgBgSQAAgEgBAAIgEgCQgEgBAAgDIAAgDIAGgDIAKgDIAGgBQAEAAABAKIAAABIAAAAQAEgGAFgDQAEgDAEAAQAGAAADADQACADAAAGQAAAFgCADQgCADgFAAIgDgBIgEgCIgCgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgDAHQgBAIAAAWIAAAKQABAEACAAIAEABQAEACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_1.setTransform(127,-10.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_2.setTransform(119.8,-10.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgCgCQgEgDgBgDIgBgQIAAgoIgHAAIgCAAIAAgDIAAgCQgBgCAJgHIACgCIADgDQAIgHADAAIACABIABABIAAAPIARAAIACABIABACIAAACIgBADIgCABIgQAAIgBABIAAACIAAAkQAAAKABACQACADAEAAIAHgBIAEgCIADACIACACQAAAFgHADQgGAEgJAAIgHgBg");
	this.shape_3.setTransform(113.2,-10.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgCgCQgEgDgBgDIgBgQIAAgoIgHAAIgCAAIAAgDIAAgCQgBgCAJgHIACgCIADgDQAIgHADAAIACABIABABIAAAPIARAAIACABIABACIAAACIgBADIgCABIgQAAIgBABIAAACIAAAkQAAAKABACQACADAEAAIAHgBIAEgCIADACIACACQAAAFgHADQgGAEgJAAIgHgBg");
	this.shape_4.setTransform(107.8,-10.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQABABAAAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_5.setTransform(101,-10.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMA3QgEgBAAgDQAAgDADgCIAEgCQACgBAAgEIABgPIAAgMIgBgOIAAgGIAAgYQgBgGgBgBIgFgBQgFgCAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAGgEIALgDIAHgBQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAIABAGIAAAFIgBA3IAAAZIACAHIAEACQAEACAAADQAAADgEABIgOABIgOgBg");
	this.shape_6.setTransform(94.6,-11.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgnA2QgEgBAAgEQAAgDAFgBIADgCQACgBAAgJIABghIgBgcQAAgLgCgCIgEgDQgEgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQADgCAEAAIAIAAIAJAAIAQAAIAKAAQASAAAIAHQAJAHAAAPQAAAQgKAIQgLAIgVAAQgGAAAAgFQAAgFAFAAQAKAAAGgFQAGgFAAgLQAAgLgGgFQgGgFgLAAIgJABIgCADIgBAHIAAAQIAAAhIAAAVIACAHIADACQAFABAAADQAAAEgFABIgQABIgQgBg");
	this.shape_7.setTransform(88.3,-11.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_8.setTransform(75.2,-10.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgCABIgCAAIgBgCQgDgBgDgHQgBgFAAgGIABgFQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQADAAAEAGIADAEQACAEAEACQAEABADAAQAFAAAEgCQACgDAAgEQAAgHgLgFIgFgDQgMgGgDgEQgFgEAAgIQAAgKAHgGQAHgHALAAIAEABIAGABIADgCIADAAQADAAAEAGQADAGABAGIgBAFQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgDgGQgEgEgCgCQgEgCgEAAQgDAAgDADQgCACgBAEQAAAEADACQADADAJAFIABABQAUAJAAAMQABALgJAHQgHAHgNAAg");
	this.shape_9.setTransform(67.9,-10.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_10.setTransform(60.6,-10.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_11.setTransform(52.6,-10.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AALA3QgEgBAAgDQAAgDAEgCIADgBQACgBAAgDIABgMQAAgYgDgFQgEgGgHAAQgEAAgDACQgEACgCAEQgCADAAAGIgBAVIABAKQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAIADABQAEACAAADQAAADgEABIgNABQgNAAgDgBQgEgCAAgDQAAgCAEgCIACgBQABAAAAAAQAAgBABAAQAAgBAAAAQABgBAAgBIABgMIAAgMIAAgMIgBghQAAgJgBgBIgGgDQgFgBAAgDQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAIAIgEIAIgCIAHgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABQABAAAAABIAAAEIgBAeIAAAEIAAACIABAAIACgCIACgDIAIgFQAEgCAFAAQANAAAGAIQAHAJgBAQIABAHIAAAOIAAAEIAAAGIADACIACABQADACAAACQAAADgDACQgDABgNAAIgNgBg");
	this.shape_12.setTransform(43.9,-11.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLA1QgKgEgIgGQgIgJgFgLQgFgLAAgNQAAgKADgJQAEgKAFgHQAIgJAKgFQALgFAMAAIAKABIAOADIACAAIAFgCIADABIACACQADAEABAGQACAGAAAEQAAAEgCABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgDAAgGgHIgFgFQgEgFgGgCQgGgCgHAAQgPAAgIAKQgJAKAAASQABAWAKAOQALAPAQAAQAGAAAHgCQAFgDAEgDIAEgFQADgEADAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIABAFQAAAIgCAEQgCAEgDAAIgBAAIgBgBQgHAEgHACIgPACQgLAAgKgEg");
	this.shape_13.setTransform(34.4,-11.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgbAyQgKgGAAgJQAAgDACgDQACgCAEAAQADAAACABIADAGQACAFAFAEQAEADAKAAQAJAAAHgEQAGgEAAgGQAAgEgCgBQgDgDgEAAIgJABIgLABQgOAAgHgFQgHgEAAgHQAAgDACgEQADgDAFgDQgEgEgCgFQgDgFAAgGQAAgMAKgIQAJgJAPAAIAHABIALACIAHgBIAIgFIACADIABACQAAADgCADQgDADgEADIACAGIABAGQAAANgJAIQgKAHgOAAIgIgBIgHgBIgCACIgBADQAAAEADACQAEABAIAAIAKgBIAMAAQALAAAFAEQAGAEAAAIQAAAMgMAJQgMAIgRAAQgPAAgJgGgAgMglQgEAFAAAHQAAAIAEAFQAEAFAGAAQAGAAAEgFQAEgFAAgHQAAgIgEgFQgEgFgGAAQgGAAgEAFg");
	this.shape_14.setTransform(21.1,-8.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAKAmQgDgBAAgDQAAgDADgCIADgBQACAAABgEIAAgLQAAgYgDgGQgDgGgIAAQgDAAgEADQgDACgCAEQgCADgBAGIAAAUIAAAKQAAABABAAQAAABAAAAQAAABABAAQAAAAABAAIACABQAEACAAADQAAADgDABIgOABIgQgBQgDgBAAgDQAAgDADgCIACgBQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBIABgJIAAgFIAAgFIAAgHIgBgRQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAAAgBAAIgEgCQgEgBAAgDQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgDIALgEIAIAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIABAEIAAAFIAAABIABAAIAAAAIACgBIACgCQAIgIAJAAQAFAAAFACQAFADAEAEQADAEACAGQABAGAAAMIAAAJIAAAGIAAADIABAIIADADIABABQAEACAAADQAAADgDABQgEABgMAAIgOgBg");
	this.shape_15.setTransform(12.3,-10.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_16.setTransform(5.6,-11.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgDABIgBAAIgBgCQgDgBgDgHQgCgFAAgGIABgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAADAGIADAEQACAEAEACQAEABADAAQAGAAACgCQADgDAAgEQAAgHgLgFIgEgDQgMgGgEgEQgFgEAAgIQAAgKAHgGQAHgHALAAIAFABIAFABIAEgCIACAAQAEAAADAGQADAGAAAGIAAAFQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgDgGQgDgEgEgCQgCgCgFAAQgDAAgDADQgCACgBAEQAAAEAEACQACADAJAFIAAABQAWAJgBAMQAAALgIAHQgHAHgNAAg");
	this.shape_17.setTransform(0.2,-10.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQABABAAAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_18.setTransform(-7.1,-10.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_19.setTransform(-15.3,-10.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgMA3QgEgBAAgDQAAgDADgCIAEgCQACgBAAgEIABgPIAAgMIgBgOIAAgGIAAgYQgBgGgBgBIgFgBQgFgCAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAGgEIALgDIAHgBQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAAAIABAGIAAAFIgBA3IAAAZIACAHIAEACQAEACAAADQAAADgEABIgOABIgOgBg");
	this.shape_20.setTransform(-21.5,-11.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgnA2QgEgBAAgEQAAgDAEgBIAEgCQACgBABgJIAAghIAAgcQgBgLgBgCIgFgDQgEgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQADgCAFAAIAHAAIAJAAIAPAAIAMAAQARAAAIAHQAJAHAAAPQAAAQgLAIQgKAIgUAAQgHAAAAgFQAAgFAGAAQAJAAAGgFQAGgFAAgLQAAgLgGgFQgGgFgMAAIgIABIgDADIgBAHIAAAQIAAAhIABAVIABAHIAEACQAFABAAADQAAAEgEABIgQABIgRgBg");
	this.shape_21.setTransform(-27.9,-11.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgOAIIgEgBIgBgDIABgEIACgDIACgDIAEgBIAEAAIAGAAIANAAIACAAIADABIABADQAAAEgCADQgCADgDAAIgEAAIgEAAIgQABIgCAAg");
	this.shape_22.setTransform(-35.3,-10.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAPA3IgBgEIAAgDIAAgCIAAAAIgDABIgEADQgEADgEACQgEABgFAAQgNAAgKgKQgIgKgBgRQAAgSALgLQAKgMARAAIAEABIAEACIABAEQAAAEgFAAIgBAAIgCAAQgJAAgFAHQgFAGAAAMQAAAMAFAJQAGAIAJAAQAGAAAFgFQAFgEAAgJIAAgVIAAgiIgBgHQgCgCgDgBIgBgBQgFgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAHgDIAJgDIAHAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAABAAABIAAAEIgBAuIABAgQAAAHABABIAFACQAFABAAACQgBAEgKAEIgIACIgGAAIgDgBg");
	this.shape_23.setTransform(-42.1,-11.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAEAIIgIgWQgEgMgEgCIgCgBQgFgBAAgDQAAgDAEgBQAEgBALgBQALABAEABQADABAAADIAAADIgCABIgCABQgBAAgBABQAAAAgBABQAAAAAAAAQAAABAAAAIABAFIAGAQIAHAOIADADIACgCIADgGIAJgTIACgKIAAgDIgCgCIgCAAQgEgCAAgCQAAgDAEgBQADgBAKgBQAIABADABQADABAAADQAAADgEABIgCABQgEACgHAQIgCAEIgDAGQgRAngFABQgFgBgOgfgAgsAFIgCgFIgFgMQgFgOgDgCIgDgBQgEgBAAgDQAAgDAEgBQADgBANgBQAKABAEABQAEABAAADIgBADIgBABIgDABQAAAAgBABQgBAAAAABQAAAAgBAAQAAABAAAAIACAGIAGAPIAGANQAAABABABQAAABABAAQAAABAAAAQABAAAAAAQACAAACgFIADgFIACgCIACgBIADABIABADIgCAHIgLAWQgEAHgDAAQgFgBgPgig");
	this.shape_24.setTransform(-53.1,-10);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_25.setTransform(-63.7,-10.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDADgCIADgBQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIAAgJIAAgFIAAgFIAAgFIAAgSQgBgEgBAAIgEgCQgFgBABgDIABgDIAEgDIALgDIAGgBQAEAAABAKIAAABIAAAAQAEgGAFgDQAEgDAEAAQAGAAADADQACADAAAGQAAAFgBADQgDADgFAAIgDgBIgEgCIgCgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgDAHQgBAIAAAWIAAAKQABAEACAAIAEABQAEACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_26.setTransform(-70.7,-10.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgLA1QgKgEgIgGQgIgJgFgLQgFgLAAgNQAAgKADgJQAEgKAFgHQAIgJAKgFQAMgFALAAIAJABIAPADIACAAIAFgCIADABIACACQADAEABAGQACAGAAAEQAAAEgCABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgFgHIgFgFQgEgFgGgCQgGgCgHAAQgPAAgIAKQgJAKAAASQAAAWAMAOQAKAPAQAAQAHAAAFgCQAGgDAEgDIAEgFQADgEADAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIABAFQAAAIgCAEQgCAEgDAAIgBAAIgBgBQgHAEgHACIgPACQgLAAgKgEg");
	this.shape_27.setTransform(-78.9,-11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whatsinourclassicturkeydinner, new cjs.Rectangle(-86.2,-22.9,224.7,22.2), null);


(lib.WFM_Logo_White_RGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(175,175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(305.4,234.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(163.9,260);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(305.6,233);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(126.2,205.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(130.7,263.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(239.5,205);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(181.9,205.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350,350);


(lib.seventeenrollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AlNBbQgmAAgbgbQgagbAAglQAAgkAagbQAbgbAmAAIKbAAQAmAAAaAbQAbAbAAAkQAAAlgbAbQgaAbgmAAg");
	this.shape.setTransform(0,0,1.076,1.076);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrollovervideo, new cjs.Rectangle(-45.7,-9.8,91.5,19.6), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AlNBbQgmAAgbgbQgagbAAglQAAgkAagbQAbgbAmAAIKbAAQAmAAAaAbQAbAbAAAkQAAAlgbAbQgaAbgmAAg");
	this.shape.setTransform(0,0,1.076,1.076);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-45.7,-9.8,91.5,19.6), null);


(lib.seventeenordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAkIgRg5IgQA5IgKAAIgWhGIALAAIAQA3IAQg3IAKAAIARA3IAQg3IAKAAIgUBGg");
	this.shape.setTransform(23.3,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgDgHAAgIQAAgIADgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAHAEIAFAEQAFAFACAHQADAGAAAIQAAAIgDAHQgCAHgFAFIgFAEIgHADQgHADgIAAIgHgBgAgKgZQgFACgEAEQgDAEgCAFQgCAFAAAFQAAAGACAFQACAFADAEQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_1.setTransform(14.1,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAkIgkg6IAAA6IgKAAIAAhGIANAAIAkA4IAAg4IAKAAIAABGg");
	this.shape_2.setTransform(6,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAkIAAhGIAWAAQAFAAAEABQAFABAEACQADADABAEQADADAAAGQAAAFgDAEQgBADgEACIgIADIgJABIgLAAIAAAggAgMgDIAKAAIAFgBIAGgBIADgEIACgFQAAgEgCgCIgDgDIgGgCIgFgBIgKAAg");
	this.shape_3.setTransform(-3.1,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgCgHAAgIQAAgIACgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAGAEIAGAEQAFAFADAHQACAGAAAIQAAAIgCAHQgDAHgFAFIgGAEIgGADQgHADgIAAIgHgBgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_4.setTransform(-10.5,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASAkIAAghIgjAAIAAAhIgKAAIAAhGIAKAAIAAAdIAjAAIAAgdIAKAAIAABGg");
	this.shape_5.setTransform(-18.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNAiQgFgCgFgFIAIgHQACAEAFACQAEADAEAAIAEgBIAGgCIACgEQACgCAAgEQAAgDgCgCIgDgEIgGgCIgFgCIgGgDIgHgCIgDgGQgCgDgBgFQAAgFADgEQACgEADgDQAEgCAEgBIAIgBIAGAAIAFACQAGACADAEIgGAHIgHgFQgDgCgFAAIgDABIgFACIgDADQgBACAAADQAAADABACIADAEIAFACIAEACIAHACIAHADQADACACAEQACADAAAGQAAAFgCAEQgCAEgDADIgIAEIgJABQgGAAgHgDg");
	this.shape_6.setTransform(-24.9,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenordernow, new cjs.Rectangle(-29.7,-8.1,60,16.3), null);


(lib.roastedturkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgCABIgCAAIgBgCQgDgBgDgHQgBgFAAgGIABgFQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQADAAAEAGIADAEQACAEAEACQAEABADAAQAFAAAEgCQACgDAAgEQAAgHgLgFIgFgDQgMgGgDgEQgFgEAAgIQAAgKAHgGQAHgHALAAIAEABIAGABIADgCIADAAQADAAAEAGQADAGABAGIgBAFQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgDgGQgEgEgCgCQgEgCgEAAQgDAAgDADQgCACgBAEQAAAEADACQADADAJAFIABABQAUAJAAAMQABALgJAHQgHAHgNAAg");
	this.shape.setTransform(119.7,-10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMA3QgEgBAAgDQAAgDADgCIAEgCQACgBAAgEIABgPIAAgMIgBgOIAAgGIAAgYQgBgGgBgBIgFgBQgFgCAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAGgEIALgDIAHgBQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAIABAGIAAAFIgBA3IAAAZIACAHIAEACQAEACAAADQAAADgEABIgOABIgOgBg");
	this.shape_1.setTransform(114.2,-11.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAEAIIgIgWQgEgMgEgCIgCgBQgFgBAAgDQAAgDAEgBQAEgBALgBQALABAEABQADABAAADIAAADIgCABIgCABQgBAAgBABQAAAAgBABQAAAAAAAAQAAABAAAAIABAFIAGAQIAHAOIADADIACgCIADgGIAJgTIACgKIAAgDIgCgCIgCAAQgEgCAAgCQAAgDAEgBQADgBAKgBQAIABADABQADABAAADQAAADgEABIgCABQgEACgHAQIgCAEIgDAGQgRAngFABQgFgBgOgfgAgsAFIgCgFIgFgMQgFgOgDgCIgDgBQgEgBAAgDQAAgDAEgBQADgBANgBQAKABAEABQAEABAAADIgBADIgBABIgDABQAAAAgBABQgBAAAAABQAAAAgBAAQAAABAAAAIACAGIAGAPIAGANQAAABABABQAAABAAAAQABABAAAAQABAAAAAAQACAAACgFIADgFIACgCIACgBIADABIABADIgCAHIgLAWQgEAHgDAAQgFgBgPgig");
	this.shape_2.setTransform(106,-10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_3.setTransform(95.4,-10.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFA3IgPgBIgHAAIgJABQgFAAgDgCQgCgBAAgDQAAgDAEgCIAEgCQACgCAAgLIABgdIgBgdQAAgLgCgBIgEgDQgEgBAAgDQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQACgBAFAAIAIAAIAJAAIAPAAIALgBQARAAAJAHQAJAHAAANQAAAKgHAHQgGAGgMACQAPACAIAGQAIAHAAANQAAAOgKAJQgKAHgSABgAgLgsQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAABIgCAJIAAAVIAAAgIAAAOIACAGQABADAEAAIAJABQAMAAAHgFQAHgFAAgLQAAgKgIgGQgHgEgNAAQgHgBAAgDQAAgGAHABQAJAAAGgFQAHgFAAgKQAAgKgGgEQgGgFgMAAg");
	this.shape_4.setTransform(85.8,-11.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAuQgLgLAAgRQAAgSALgKQAMgMAQAAQAPAAAIAJQAJAIAAANQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgHgFgFQgFgFgHAAQgIAAgFAIQgEAHAAALQAAAMAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLgAgFgdQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgCgEIABgBIABgBIAZgQIADgBIABgBQACAAADAEQACADAAACQAAADgFACIgaAMIgBABIgBAAg");
	this.shape_5.setTransform(72.4,-11.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgCgCQgDgDgCgDIgBgQIAAgoIgGAAIgDAAIgBgDIAAgCQABgCAHgHIADgCIAEgDQAHgHADAAIACABIAAABIAAAPIARAAIAEABIAAACIAAACIAAADIgEABIgPAAIgBABIgBACIAAAkQAAAKACACQABADAFAAIAHgBIAEgCIAEACIABACQgBAFgGADQgHAEgHAAIgIgBg");
	this.shape_6.setTransform(65.8,-10.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_7.setTransform(60.8,-11.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAPA3IgBgEIAAgDIAAgCIgBAAIgCABIgEADQgEADgEACQgDABgGAAQgOAAgIgKQgKgKABgRQgBgSALgLQAKgMARAAIAEABIAEACIABAEQAAAEgFAAIgCAAIgCAAQgIAAgFAHQgFAGAAAMQAAAMAGAJQAFAIAIAAQAIAAAEgFQAEgEAAgJIAAgVIAAgiIAAgHQgBgCgEgBIgCgBQgEgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAIgDIAIgDIAHAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAABAAABIgBAEIAAAuIAAAgQABAHABABIAGACQADABAAACQABAEgMAEIgHACIgGAAIgDgBg");
	this.shape_8.setTransform(54.5,-11.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AARAnIgBgEIAAgFIgBgBIgDACIgBABQgDAEgFABQgDADgGAAQgGAAgFgDQgFgCgDgEQgEgEgBgGQgCgHAAgPIAAgFIAAgFIAAgCQAAgHgBgBQAAgBAAAAQAAAAgBgBQAAAAgBAAQgBgBAAAAIgDgBQgFgBAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAHgDIAKgDIAIgBQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABAGIAAADIgBAcQAAAPAEAFQADAHAHgBQAIAAAEgHQAEgIAAgSIAAgFIgBgIQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgEgBQgEgBAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAHgDIAKgDIAIgBQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAGIAAAEIgBAfIAAAMIAAAFQABADAEACIABAAQAFACAAADIgCADIgEACIgLAEIgIABQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAg");
	this.shape_9.setTransform(45.1,-10.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDADgCIACgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIABgJIAAgFIgBgFIAAgFIAAgSQgBgEgCAAIgDgCQgFgBAAgDIACgDIAEgDIAKgDIAHgBQAEAAABAKIAAABIABAAQADgGAFgDQAEgDAEAAQAFAAADADQAEADAAAGQAAAFgCADQgDADgEAAIgFgBIgDgCIgBgDQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgCAHQgCAIAAAWIABAKQABAEACAAIACABQAFACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_10.setTransform(37.9,-10.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLA1QgKgEgIgGQgJgJgEgLQgFgLAAgNQAAgKADgJQAEgKAGgHQAHgJAKgFQAMgFALAAIAKABIAOADIABAAIAGgCIADABIACACQACAEACAGQACAGAAAEQAAAEgCABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgDAAgGgHIgFgFQgEgFgGgCQgGgCgHAAQgPAAgIAKQgIAKgBASQAAAWALAOQALAPAQAAQAGAAAHgCQAFgDAFgDIADgFQADgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIABAFQAAAIgCAEQgCAEgDAAIgBAAIgBgBQgHAEgHACIgPACQgKAAgLgEg");
	this.shape_11.setTransform(29.7,-11.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgCgCQgDgDgCgDIgBgQIAAgoIgHAAIgCAAIgBgDIAAgCQAAgCAIgHIADgCIAEgDQAHgHADAAIACABIAAABIAAAPIARAAIADABIABACIAAACIgBADIgDABIgPAAIgBABIgBACIAAAkQABAKABACQABADAFAAIAHgBIAEgCIAEACIABACQgBAFgGADQgHAEgIAAIgHgBg");
	this.shape_12.setTransform(17.5,-10.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgXAdQgLgLAAgRQAAgQAMgMQALgMAQAAQANAAAJAHQAIAGAAAJQAAAEgCACQgCACgEAAQgFAAgBgCQgDgBgDgHQgCgFgDgCQgDgCgEAAQgIAAgGAGQgEAHAAALQgBANAIAJQAGAIALAAIAHgBIAGgDIADgCQAEgDACAAIADABIABACIgCAFIgEAFQgGAFgGACQgHADgHAAQgPAAgLgLg");
	this.shape_13.setTransform(10.9,-10.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_14.setTransform(2.9,-10.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVA3QgDgCAAgDQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIACgBQABAAAAgBQABAAAAgBQAAAAAAgBQABAAAAgBIAAgJIAAgHIAAgkIgIAAIgDgBIAAgDIAAgBIABgDIACgBIAIAAIgBgGIAAgFQAAgMAHgGQAHgHAMAAQAIAAAGAEQAFAEAAAGQAAAEgCABQgCACgDAAIgFgBIgDgDIgBgDQgDgFgFAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQgBACAAADIABAIIABAMIAMAAIACABIABADIAAABIgBADIgCABIgLAAIAAAmIAAANQAAABABABQAAAAAAABQAAAAABAAQAAABAAAAIADABQAFACAAADQAAADgEABIgOABIgPgBg");
	this.shape_15.setTransform(-2.6,-11.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDAEgCIABgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIACgJIAAgFIgBgFIAAgFIgBgSQAAgEgCAAIgDgCQgFgBAAgDIABgDIAFgDIAKgDIAIgBQADAAABAKIAAABIABAAQADgGAEgDQAFgDAEAAQAFAAADADQAEADAAAGQAAAFgDADQgCADgEAAIgFgBIgCgCIgCgDQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgCAHQgCAIAAAWIABAKQABAEACAAIACABQAFACAAADQAAADgEABIgOABQgLAAgEgBg");
	this.shape_16.setTransform(-8.1,-10.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_17.setTransform(-15.2,-10.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgnA2QgEgBAAgEQAAgDAFgBIADgCQABgBACgJIAAghIAAgcQgBgLgCgCIgEgDQgEgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQACgCAFAAIAIAAIAJAAIAPAAIALAAQASAAAIAHQAJAHAAAPQAAAQgLAIQgKAIgUAAQgHAAAAgFQAAgFAFAAQAKAAAGgFQAGgFAAgLQAAgLgGgFQgGgFgMAAIgIABIgCADIgBAHIAAAQIAAAhIAAAVIABAHIAEACQAFABAAADQAAAEgFABIgPABIgRgBg");
	this.shape_18.setTransform(-23.6,-11.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOAIIgEgBIAAgDIAAgEIACgDIACgDIAFgBIADAAIAGAAIANAAIACAAIADABIABADQAAAEgCADQgCADgEAAIgDAAIgFAAIgPABIgCAAg");
	this.shape_19.setTransform(-31,-10.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgiAzQgEgEAAgEQAAgEADgDQACgCAEAAIADAAIADACIACACQAAABABABQAAAAABABQAAAAAAAAQABABAAAAQAEAAAEgGQAEgGAAgGQAAgHgFgLIgBgCIgMgaIgHgPQgBgDgFgCIAAAAIgEgCIAAgCQAAgEAEgBQAEgBALgBQALABAEABQADABAAADIAAADIgCABIgCABQgBAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAIABAGIAGAQIAGAOQAAABABABQAAAAAAABQABAAAAAAQABABAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIAFgMIAGgPIACgHQAAgDgEgCQgFgDAAgBQAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAQADgBAJgBQAJABADABQABAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAADgEABIgDABQgEADgFANIgCAGIgKAXQgNAggHAJQgIAKgLAAQgGAAgDgDg");
	this.shape_20.setTransform(-37.3,-8.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgDgCQgCgDgBgDIgBgQIAAgoIgHAAIgDAAIgBgDIAAgCQABgCAHgHIAEgCIACgDQAJgHACAAIACABIABABIAAAPIAQAAIAEABIAAACIAAACIAAADIgEABIgPAAIgBABIAAACIAAAkQAAAKABACQACADAEAAIAGgBIAGgCIACACIABACQAAAFgGADQgHAEgHAAIgIgBg");
	this.shape_21.setTransform(-43.8,-10.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDADgCIACgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIABgJIAAgFIgBgFIAAgFIAAgSQgBgEgCAAIgDgCQgFgBABgDIABgDIAEgDIAKgDIAHgBQAEAAABAKIAAABIABAAQADgGAFgDQAEgDAEAAQAGAAADADQADADAAAGQAAAFgCADQgDADgEAAIgFgBIgDgCIgBgDQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgCAHQgCAIAAAWIABAKQABAEABAAIADABQAFACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_22.setTransform(-49.3,-10.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQABABAAAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_23.setTransform(-56.4,-10.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgnA2QgEgBAAgEQAAgDAEgBIAEgCQACgBABgJIAAghIAAgcQgBgLgCgCIgEgDQgEgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQACgCAGAAIAHAAIAJAAIAPAAIALAAQASAAAIAHQAJAHAAAPQAAAQgLAIQgKAIgUAAQgHAAAAgFQAAgFAGAAQAJAAAGgFQAGgFAAgLQAAgLgGgFQgGgFgMAAIgIABIgDADIAAAHIAAAQIAAAhIAAAVIABAHIAEACQAFABAAADQAAAEgEABIgQABIgRgBg");
	this.shape_24.setTransform(-64.9,-11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.roastedturkey, new cjs.Rectangle(-71.7,-22.9,196.9,22.2), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalebackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D6E47").s().p("A6bFUIAAqnMA04AAAIAAKng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalebackground, new cjs.Rectangle(-169.2,-34,338.5,68), null);


(lib.herbstuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkA0QgEgBAAgDQAAgDADgBIAEgCQACgCAAgGIAAgZIAAgLIAAgbQAAgGgCgBIgEgBQgEgCgBgCQAAgBABAAQAAgBAAAAQAAAAAAgBQABAAAAAAQABgCAEgBIAKgDIAIgCIADABIABAEIAAAEIAAABIAAABIADgCIADgCQAFgEAEgBQADgCAFAAQAPAAAJAKQAIALABAQQAAARgLAMQgKAMgPAAQgHAAgBgCQgEgCAAgDIACgDIADgBIACABIACAAQAIAAAGgHQAFgHAAgLQAAgNgFgIQgGgIgJAAQgHAAgEAEQgFAFAAALIAAAwIAAAHIACAFIAEACIADAAIACACIABACQAAADgFABIgQABIgOgBg");
	this.shape.setTransform(98.9,-8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAiAmQgEgBAAgDQAAgDAEgCIACgBQACgBACgDIAAgOQAAgVgDgGQgDgGgIAAQgJAAgDAHQgFAIAAASIAAAEIABALQAAABABAAQAAABAAAAQABABAAAAQAAAAABAAIACABQAEACgBADQABADgEABQgDABgMAAQgKAAgDgBQgEgBAAgDQAAgDAEgCIADgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAAAIAAgMQAAgYgCgGQgEgGgHAAQgFAAgDADQgEACgCAEIgDAKIAAATIAAAKIADADIADABQADACAAADQAAADgDABIgOABQgMAAgDgBQgEgBAAgDQAAgDAEgCIACgBQAAAAABAAQAAAAABgBQAAAAAAgBQAAAAABgBIABgJIAAgFIgBgFIAAgFIAAgSQgBgEgBAAIgEgCQgFgBABgDIABgDIAEgDIAMgEIAHgBQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIAAAFIAAAAIAAABIABAAIAAAAIACgBIABgBQAJgJAKAAIAGABQAEABADACQACACADAEIADADIADgCIAEgDQAFgFAEgCQADgBAFAAQAIAAAHADQAGAEADAGQAEAHAAAWIAAAHIAAAFIAAADIABAGQAAABAAAAQABABAAAAQAAABABAAQAAAAAAAAIACABQAFACAAADQAAADgFABQgDABgLAAIgPgBg");
	this.shape_1.setTransform(87.6,-10.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_2.setTransform(78.4,-11.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDAEgCIACgBQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgJIAAgFIAAgFIAAgFIgBgSQAAgEgCAAIgDgCQgEgBgBgDIABgDIAGgDIAKgDIAHgBQADAAABAKIAAABIAAAAQAEgGAEgDQAFgDAEAAQAFAAADADQADADAAAGQAAAFgCADQgCADgFAAIgDgBIgDgCIgDgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgDAHQgBAIAAAWIAAAKQACAEACAAIADABQAEACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_3.setTransform(73.6,-10.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AALA3QgEgBAAgDQAAgDAEgCIADgBQABgBABgDIABgMQAAgYgDgFQgDgGgJAAQgDAAgDACQgEACgCAEQgCADAAAGIgBAVIABAKQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAIADABQAEACAAADQAAADgEABIgNABQgMAAgEgBQgEgCAAgDQAAgCAEgCIACgBQABAAAAAAQAAgBABAAQAAgBAAAAQABgBAAgBIABgMIAAgMIAAgMIgBghQAAgJgCgBIgFgDQgFgBAAgDQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAIAIgEIAIgCIAHgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABQABAAAAABIAAAEIgBAeIAAAEIAAACIABAAIACgCIACgDIAIgFQAEgCAFAAQANAAAGAIQAHAJgBAQIABAHIAAAOIAAAEIAAAGIADACIACABQADACAAACQAAADgDACQgDABgMAAIgOgBg");
	this.shape_4.setTransform(65.9,-11.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSA3QgIgCgGgDQgDgCgCgGQgCgHAAgJQAAgDABgCQABAAAAgBQABAAAAAAQABAAAAgBQABAAABAAQADAAADAHIADADQAFAJAFAEQAGAEAHAAQAIAAAGgFQAGgFgBgIQAAgKgVgKIgCgBQgTgHgGgHQgGgHAAgLQAAgNAKgJQAKgJAQAAIAIABIALACIADgCIACAAIAEABIADAEIAEAJIABAJIgBAEQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgEAAgEgGIgBgBQgFgGgEgDQgFgCgHAAQgIAAgFAEQgEAEAAAHQAAAGAEAEQAEAEAPAHIAEABQANAGAHAFQADADADAGQACAFAAAGQAAAPgLAJQgLAJgTAAQgIAAgJgCg");
	this.shape_5.setTransform(57.1,-11.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_6.setTransform(44.4,-10.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIAgQgEgHgLgZIgEgLQgGgPgDgCIgCgBQgEgBgBgDQAAgDAFgBQADgBAMgBQALABADABQAEABAAADIAAADIgCABIgCABQgBAAAAABQgBAAAAABQgBAAAAAAQAAABAAAAIACAGIAFAPIAGAOQAAABABAAQAAABAAAAQABABAAAAQAAAAAAAAIADgCIADgGIAJgTIACgKIAAgDIgCgCIgCAAQgEgCAAgCQAAgDAEgBQAEgBAJgBQAIABADABQADABABADQAAADgFABIgDABQgDACgHAPIgBAFIgEAGQgRAngEABQgDAAgFgIg");
	this.shape_7.setTransform(36.5,-10);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDADgCIACgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIABgJIAAgFIgBgFIAAgFIAAgSQgBgEgCAAIgDgCQgFgBAAgDIACgDIAEgDIAKgDIAIgBQADAAABAKIAAABIABAAQADgGAFgDQAEgDAEAAQAFAAADADQAEADAAAGQAAAFgCADQgDADgEAAIgFgBIgDgCIgBgDQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgCAHQgCAIAAAWIABAKQABAEABAAIADABQAFACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_8.setTransform(29.8,-10.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_9.setTransform(22.7,-10.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSA3QgIgCgGgDQgDgCgCgGQgCgHAAgJQAAgDACgCQAAAAAAgBQABAAAAAAQABAAAAgBQABAAABAAQADAAAEAHIABADQAFAJAGAEQAGAEAIAAQAHAAAGgFQAFgFABgIQAAgKgWgKIgDgBQgSgHgGgHQgGgHAAgLQAAgNAKgJQAKgJAQAAIAJABIAKACIADgCIADAAIADABIADAEIAEAJIACAJIgBAEQgBABAAAAQgBAAAAAAQgBABAAAAQAAAAgBAAQgEAAgEgGIgBgBQgEgGgGgDQgFgCgGAAQgIAAgEAEQgFAEAAAHQAAAGAEAEQAEAEAQAHIACABQAOAGAGAFQAFADACAGQACAFAAAGQAAAPgLAJQgLAJgSAAQgJAAgJgCg");
	this.shape_10.setTransform(14.3,-11.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOAIIgDgBIgBgDIABgEIABgDIACgDIAFgBIADAAIAGAAIANAAIACAAIADABIABADQAAAEgBADQgDADgEAAIgDAAIgFAAIgPABIgCAAg");
	this.shape_11.setTransform(7.3,-10.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_12.setTransform(0.4,-10.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgCgCQgEgDgBgDIgBgQIAAgoIgHAAIgCAAIAAgDIAAgCQgBgCAJgHIACgCIADgDQAIgHADAAIACABIAAABIAAAPIASAAIACABIABACIAAACIgBADIgCABIgQAAIgBABIgBACIAAAkQABAKABACQACADAEAAIAHgBIAEgCIADACIACACQAAAFgHADQgGAEgJAAIgHgBg");
	this.shape_13.setTransform(-6.5,-10.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOAIIgEgBIgBgDIABgEIACgDIACgDIAEgBIAEAAIAGAAIANAAIACAAIADABIABADQAAAEgCADQgCADgDAAIgEAAIgEAAIgQABIgCAAg");
	this.shape_14.setTransform(-11.9,-10.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgiAzQgEgEAAgEQAAgEADgDQACgCAEAAIADAAIADACIACACQAAABABABQAAAAABABQAAAAAAAAQABABAAAAQAEAAAEgGQAEgGAAgGQAAgHgFgLIgBgCIgMgaIgHgPQgBgDgFgCIAAAAIgEgCIAAgCQAAgEAEgBQAEgBALgBQALABAEABQADABAAADIAAADIgCABIgCABQgBAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAIABAGIAGAQIAGAOQAAABABABQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIAFgMIAGgPIACgHQAAgDgEgCQgFgDAAgBQAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAQADgBAJgBQAJABADABQABAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAADgEABIgDABQgEADgFANIgCAGIgKAXQgNAggHAJQgIAKgLAAQgGAAgDgDg");
	this.shape_15.setTransform(-18.2,-8.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAPA3IgBgEIAAgDIAAgCIgBAAIgCABIgDADQgFADgDACQgFABgEAAQgOAAgKgKQgJgKAAgRQAAgSAKgLQALgMAQAAIAFABIADACIACAEQAAAEgFAAIgCAAIgCAAQgIAAgFAHQgFAGAAAMQAAAMAGAJQAFAIAIAAQAIAAAEgFQAFgEgBgJIAAgVIAAgiIgBgHQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBAAAAAAIgDgBQgEgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAIgDIAJgDIAHAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAABAAABIgBAEIAAAuIAAAgQABAHABABIAFACQAEABAAACQAAAEgLAEIgHACIgGAAIgDgBg");
	this.shape_16.setTransform(-26.3,-11.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQABABAAAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_17.setTransform(-35.1,-10.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_18.setTransform(-43.3,-10.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AARAmQgIgYgFgFQgEgFgJAAQgFAAgBgEQABgFAFAAQAMAAAFgFQAGgFABgKQgBgKgGgFQgGgFgLAAIgIAAIgDADIgBAHIAAAPIAAAhIABAXQAAAGACABIACABQAGACAAADQgBADgEACIgQABIgQgBQgFgCAAgDQABgDAEgCIADgCQACgBABgJIAAggIAAgdQAAgLgCgBIgEgDQgFgCAAgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQADgBAFAAIAQAAIAQAAIALgBQARAAAIAHQAKAHgBAOQABAKgHAHQgFAIgLACIAAABQAJABAEAFQAFAFAEANIABAHQADAMAFAAIACAAIADAAIADABIABADQgBADgEADQgEACgIAAQgPAAgEgSg");
	this.shape_19.setTransform(-52.6,-11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.herbstuffing, new cjs.Rectangle(-60.2,-22.9,166,22.2), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A6Fj2MA0LAAAIAAHuMg0LAAAg");
	this.shape.setTransform(0,0,0.955,0.99);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-25.5,321,51), null);


(lib.classicturkeydinnerfor8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVAZQgJgKAAgOQAAgOAJgLQAKgKAPAAQAMAAAHAIQAIAHAAAMQAAAEgBACQgCABgFAAIgYAAIgDgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAgBIADAAIANAAIADgBIABgCQAAgGgEgFQgEgEgGAAQgHAAgEAHQgEAHAAAKQAAAIAFAIQAFAIAIgBIAIgBIAHgCIACgCQADgDADAAIACAAIABADIgCAEIgFAFQgFAEgGACQgFADgGAAQgNAAgKgKg");
	this.shape.setTransform(172.8,-10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgTAhQgDgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABgBIACAAIACgDIABgIIAAgEIAAgGIAAgDIgBgPQAAgBAAgBQAAgBgBAAQAAgBAAAAQAAAAgBgBIgDgBQgEgBAAgCIABgDIAFgCIAIgDIAGgBQAEAAAAAIIAAACIAAAAQAEgFAEgDQADgDAEAAQAFAAACADQADADAAAEQAAAFgCADQgCACgEAAIgDAAIgDgCIgCgDQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAQgFAAgBAHQgCAGAAATIABAJQAAABAAAAQAAABABAAQAAABAAAAQABAAAAAAIADABQAEACAAACQAAABAAAAQgBABAAAAQgBABAAAAQgBABgBAAIgMABIgNgBg");
	this.shape_1.setTransform(166.9,-10.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAZQgJgKAAgPQAAgOAKgKQAKgKANAAQAOAAAJAJQAKAKgBAPQAAAOgJAKQgKALgOAAQgOgBgJgJgAgLgTQgEAGAAAIQgBAMAGAKQAFAIAIAAQAGAAAEgGQAEgFAAgJQAAgLgFgKQgGgJgHAAQgHABgDAFg");
	this.shape_2.setTransform(160.6,-10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZAvQgEgBAAgDQAAgDAEgCIADgBQAAAAABgBQAAAAAAAAQAAgBAAAAQAAgBAAgBIABgMIAAgDIAAgbIAAgRIgIAWQgUAygDAAQgCAAgFgHIgMgdIgPggIgBAZIAAASIABAMQAAABAAABQAAAAAAABQAAAAABAAQAAABAAAAIADABQAEACAAADQAAACgDACIgMABIgKgBQgDgCAAgCQAAgDADgBQABgBABAAQAAgBABAAQAAAAABgBQAAAAAAAAIACgVIABglIAAgCIgBgJQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgEgCQgEgBAAgDQAAgDADgBQADgBAKAAIAJABIADAAQABABAFAMIADAJIACAFQAQAnAAAAQACAAAGgOIAOglIACgEQACgHACgCQAAgBABAAQAAAAAAgBQABAAAAAAQABAAABAAIAJgBIALABQABAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAADgDABIgCABIgDAEIgBAMIABAlIACAUQAAAAAAAAQAAABABAAQAAAAABABQAAAAABAAIABABIACABIABADQAAADgDABIgPABIgNgBg");
	this.shape_3.setTransform(150.9,-11.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnAoQgMgJAAgQQAAgIAEgHQADgFAJgGIAAgBIgEgGIgBgHQAAgKAHgHQAIgGAMAAQAIAAAFADQAFADAAAEIgBADIgDABIgFgCQgEgCgEAAQgFAAgEAEQgDADAAAGIABAEQAAABABAAQAAABAAAAQAAABABAAQAAAAABABIAEADIAEABIABABIABABQAAAAAAABQgBAAAAAAQAAABgBABQAAAAgBABQgCADgCAAIgDgBIgFgCQgDAEgCADQgCAFAAAGQAAANAIAIQAIAIANAAQAKAAAHgFQAGgGAAgJQAAgGgDgDQgCgDgFAAQgEAAgDADQgDACAAAEIAAACIAAAAIAAABIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgCgCAAgDQAAgKAdgMIACgBQAHgEAEgEQAEgEAAgEQAAgEgCgBQgBgCgEAAIgCABIgDAAIgCgBIgBgCQAAgDAEgCQADgCAGAAQAHAAAEAEQAEAEAAAGQAAAJgHAGQgHAHgPAGQAGABAEAFQADAFAAAHQAAAFgCAFQgCAEgEAEQgGAHgJADQgJADgLAAQgUAAgMgJg");
	this.shape_4.setTransform(136,-11.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgEAiIgHgBIgCABIgCABIgCgBIgBgBQgCgBgCgGQgCgFAAgFIABgDQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQADAAADAFIADAEQACADADABQAEACADAAQAEAAACgCQADgCAAgEQAAgGgKgFIgEgCQgKgFgEgDQgEgFAAgGQAAgIAGgGQAGgFAKAAIAEAAIAEABIAEgBIACgBQADAAADAFQADAGAAAFIgBAEQgBAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDgBIgDgEQgDgFgDgBQgCgCgEAAQgDAAgCACQgCADAAADQAAADACACQACADAIAEIAAAAQATAIAAALQAAAJgHAGQgHAHgLAAg");
	this.shape_5.setTransform(123.6,-10.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVAZQgJgKAAgOQAAgOAJgLQAKgKAOAAQANAAAHAIQAIAHAAAMQAAAEgBACQgBABgGAAIgYAAIgDgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAgBIADAAIANAAIAEgBIAAgCQAAgGgEgFQgFgEgFAAQgIAAgDAHQgEAHAAAKQAAAIAFAIQAGAIAHgBIAIgBIAGgCIADgCQAEgDACAAIABAAIABADIgBAEIgEAFQgGAEgGACQgFADgGAAQgOAAgJgKg");
	this.shape_6.setTransform(117.3,-10);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDAoIgFgDQgDgCgBgFIAAgNIAAgiIgHAAIgBgBIgBgCIAAgBQAAgDAHgFIADgDIACgCQAHgGACAAIACABIAAABIAAANIAPAAIACABIABACIAAABIgBADIgCABIgNAAIgBABIgBABIAAAfQAAAJACADQABACAEAAIAFgBIAFgBIACAAIABACQAAAEgFAEQgGADgHAAIgHgBg");
	this.shape_7.setTransform(111.5,-10.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLAvQgDgBAAgDQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIACgBIACgDIABgHIAAgFIAAgFIAAgHIgBgMQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgCgBQgFgCAAgCIABgDIAFgCIAJgDIAHgBIACABIABAEIAAAEIAAADIgBAQIAAARIAAAJQABAAAAABQAAAAABABQAAAAAAAAQABABAAAAIACABQABAAABABQAAAAABABQAAAAAAABQAAAAABABQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAAAIgNABIgMgBgAgIggQgCgDAAgDQAAgEADgCQADgDAEAAQAEAAADACQADADgBADQAAAEgCACQgDADgEAAQgFAAgDgCg");
	this.shape_8.setTransform(107.3,-11.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEAwIgNgBIgGAAIgIABQgEAAgDgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgDADgBIAFgDQAAgBABgKIABgZIgBgZQgBgJAAgBIgFgDQgDgBAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQACgCAEAAIAHAAIAHAAIAOAAIAJAAQAOAAAJAGQAHAGAAALQAAAJgFAFQgGAGgKACQANABAHAGQAHAGAAALQAAAMgJAHQgIAHgRAAgAgKgmIgCACIgBAIIgBATIAAAbIABANIABAFQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIAIABQALAAAFgEQAGgFAAgJQAAgJgHgEQgFgFgMAAQgGAAABgDQgBgFAGAAQAIAAAGgEQAFgDAAgJQAAgJgFgEQgFgEgLAAg");
	this.shape_9.setTransform(100.8,-11.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgKAwQgEgBAAgEQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBIAEgBIABgGIAAgMIAAgLIAAgMIAAgEIAAgWQgBgFgBAAIgEgCQgEgBAAgDIABgCIAGgDIAJgDIAGgBQAAAAABABQAAAAABAAQAAAAAAAAQAAABABAAIABAEIAAAFIgBAvIAAAWIABAHIAEABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgMAAIgMAAg");
	this.shape_10.setTransform(90.8,-11.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLAwQgDgBAAgEQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBIAEgBIABgGIABgMIAAgLIAAgMIAAgEIgBgWQgBgFgBAAIgEgCQgEgBAAgDIABgCIAGgDIAJgDIAGgBQABAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIABAEIAAAFIgBAvIAAAWIACAHIADABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgMAAIgNAAg");
	this.shape_11.setTransform(87.1,-11.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAMAfIgEgDIgDABQgHAGgIAAQgKAAgGgGQgGgGAAgJQAAgLAIgEQAIgHANABIAFAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAADgEAAQgGAAgEADQgEADAAAGQAAAFADADQAEADAGAAQAFAAADgCQADgDAAgHIAAgYQAAgGgDgDQgCgDgEAAIgGABIgFAFIgCACQgEAEgEAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgGAIgFQAHgEAMAAQAHAAAFACQAFACADAEQACADABAEIABANIAAAUIAAAGIACACIACABQAFABAAACQAAADgFADQgEADgGAAQgDAAgDgEg");
	this.shape_12.setTransform(81.9,-10);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAdAhQAAAAgBgBQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgCADgCIADgBIACgEIABgLQAAgTgCgFQgDgFgHAAQgIAAgEAHQgDAGAAAPIAAAEIABAJIACAEIACAAQABABABAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgCABQgEABgKAAIgLgBQgBAAgBgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAABAAIACgCQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIABgKQAAgUgDgGQgCgFgIAAQgDAAgDACQgDACgCAEQgCADAAAFIgBARIABAIQAAABAAAAQAAABABAAQAAABAAAAQABAAAAAAIACACQABAAABAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBABgBAAIgLABQgLAAgDgBQgDgBAAgDQAAgBAAAAQAAgBABAAQAAgBABAAQABAAAAgBIACAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgIIAAgEIAAgGIAAgDIAAgPQgBgBAAgBQAAgBAAAAQAAgBgBAAQAAAAgBgBIgDgBQgDgBAAgCQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAEgCIAJgEIAHgBIADABIABAEIAAADIAAABIAAABIABAAIAAAAIACgCIAAgBQAIgHAJAAIAFABQADABADACIADAEIAEADIACgCIADgDIAIgFIAHgBQAHAAAHADQAFADACAGQAEAGAAASIAAAHIAAAEIAAADIAAAFIACADIACAAQABABABAAQAAAAABABQAAAAAAABQABAAAAABQAAADgEABQgDABgKAAQgJAAgEgBg");
	this.shape_13.setTransform(72.2,-10.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgPAwQgIgCgEgCQgDgCgCgGQgBgFAAgIQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQADAAADAGIACADQAEAHAFADQAFAEAHAAQAHAAAFgFQAEgEABgGQAAgJgUgJIgCgBQgPgGgGgGQgFgGAAgJQAAgMAIgHQAKgIANAAIAIABIAJACIACgCIACgBIADABIADAEIADAIIACAIIgBADIgDACQgDAAgEgFIgBgBQgEgFgEgDQgFgCgFAAQgGAAgEADQgFAEAAAGQAAAFAEAEQADADAOAGIACACQAMAFAGADQADAEACAEQACAFAAAFQgBANgIAIQgKAHgQAAQgIAAgHgBg");
	this.shape_14.setTransform(62.3,-11.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgGAUIgBgCIABgCIABgCIAEgHIABgFIAAgCIgDAAIgEgEQgCgCAAgEQAAgEADgDQADgDADAAQAEAAADAEQADAEAAAGQAAAEgCAEQgBAFgFAHIgDAFIgCACIgDgBg");
	this.shape_15.setTransform(53.2,-6.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgEAiIgHgBIgCABIgCABIgCgBIgBgBQgCgBgCgGQgCgFAAgFIABgDQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQADAAADAFIADAEQACADADABQAEACADAAQAEAAACgCQADgCAAgEQAAgGgKgFIgEgCQgKgFgEgDQgEgFAAgGQAAgIAGgGQAGgFAKAAIAEAAIAEABIAEgBIACgBQADAAADAFQADAGAAAFIgBAEQgBAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDgBIgDgEQgDgFgDgBQgCgCgEAAQgDAAgCACQgCADAAADQAAADACACQACADAIAEIAAAAQATAIAAALQAAAJgHAGQgHAHgLAAg");
	this.shape_16.setTransform(48.3,-10.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTAhQgDgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABgBIACAAIACgDIABgIIAAgEIAAgGIAAgDIgBgPQAAgBAAgBQAAgBAAAAQgBgBAAAAQAAAAgBgBIgDgBQgEgBAAgCIABgDIAFgCIAIgDIAGgBQAEAAAAAIIAAACIAAAAQAEgFAEgDQADgDAEAAQAFAAACADQADADAAAEQAAAFgCADQgCACgEAAIgDAAIgDgCIgCgDQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAQgFAAgBAHQgCAGAAATIABAJQAAABAAAAQAAABABAAQAAABAAAAQABAAAAAAIADABQAEACAAACQAAABAAAAQgBABAAAAQgBABAAAAQgBABgBAAIgMABIgNgBg");
	this.shape_17.setTransform(43.1,-10.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgVAZQgJgKAAgOQAAgOAJgLQAKgKAOAAQANAAAHAIQAIAHAAAMQAAAEgBACQgBABgGAAIgYAAIgDgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAgBIADAAIANAAIADgBIABgCQAAgGgEgFQgEgEgGAAQgHAAgEAHQgEAHAAAKQAAAIAFAIQAGAIAHgBIAIgBIAHgCIACgCQAEgDACAAIACAAIAAADIgBAEIgFAFQgFAEgGACQgFADgGAAQgNAAgKgKg");
	this.shape_18.setTransform(37,-10);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgDAoIgFgDQgDgCgBgFIAAgNIAAgiIgHAAIgBgBIgBgCIAAgBQAAgDAHgFIADgDIACgCQAHgGACAAIACABIAAABIAAANIAPAAIACABIABACIAAABIgBADIgCABIgNAAIgBABIgBABIAAAfQAAAJACADQABACAEAAIAFgBIAFgBIACAAIABACQAAAEgFAEQgGADgHAAIgHgBg");
	this.shape_19.setTransform(31.2,-10.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgDAoIgFgDQgDgCgBgFIAAgNIAAgiIgHAAIgBgBIgBgCIAAgBQAAgDAHgFIADgDIACgCQAHgGACAAIACABIAAABIAAANIAPAAIACABIABACIAAABIgBADIgCABIgNAAIgBABIgBABIAAAfQAAAJACADQABACAEAAIAFgBIAFgBIACAAIABACQAAAEgFAEQgGADgHAAIgHgBg");
	this.shape_20.setTransform(26.6,-10.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMAfIgEgDIgDABQgHAGgIAAQgKAAgGgGQgGgGAAgJQAAgLAIgEQAIgHANABIAFAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAADgEAAQgGAAgEADQgEADAAAGQAAAFADADQAEADAGAAQAFAAADgCQADgDAAgHIAAgYQAAgGgDgDQgCgDgEAAIgGABIgFAFIgCACQgEAEgEAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBQAAgGAIgFQAHgEAMAAQAHAAAFACQAFACADAEQACADABAEIABANIAAAUIAAAGIACACIACABQAFABAAACQAAADgFADQgEADgGAAQgDAAgDgEg");
	this.shape_21.setTransform(20.8,-10);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLAwQgCgBAAgEQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIADgBIACgGIABgMIAAgLIAAgMIAAgEIgBgWQgBgFgBAAIgEgCQgEgBAAgDIABgCIAGgDIAJgDIAGgBQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIABAEIAAAFIgBAvIABAWIACAHIADABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgMAAIgNAAg");
	this.shape_22.setTransform(15.2,-11.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgiAvQgDgBAAgDQAAgCAEgDIADgBQABgBABgIIAAgcIAAgZQAAgJgBgBIgFgCQgDgCAAgDQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQACgCAEABIAHAAIAIAAIANAAIAJgBQAQAAAHAHQAHAGAAANQAAANgJAHQgJAHgRAAQgHAAABgFQAAgDAEAAQAJgBAFgEQAFgEAAgKQAAgJgFgFQgFgDgLAAIgGAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAgBAAIAAAHIAAANIAAAdIAAATQAAAEABABIAEABQAEACgBADQABADgEABIgOABIgPgBg");
	this.shape_23.setTransform(9.7,-11.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgeAsQgDgDAAgEQAAgEACgCQADgCADAAIADABIACABIACACQAAABABABQAAAAAAAAQABABAAAAQAAAAABAAQADAAADgFQAEgFAAgFQAAgFgFgLIAAgBIgLgXIgGgNQgBgCgEgCIgDgCIgBgCQAAgDAEgBQADgBAKgBQAJABAEABQAAAAABABQABAAAAAAQAAABABAAQAAABAAABIgBACIgBABIgCABQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAIACAFIAFANIAEANQABAAAAABQABABAAAAQAAABABAAQAAAAAAAAIACgDIAFgKIAEgOIACgGQAAgCgEgCQgDgDAAgBQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAQADgBAHgBQAIABADABQABAAAAABQABAAAAAAQAAABABAAQAAABAAABQAAACgEABIgDABQgEACgEALIgCAFIgIAVQgLAbgGAJQgHAHgKAAQgFAAgDgCg");
	this.shape_24.setTransform(-1.3,-8.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAMAfIgEgDIgDABQgHAGgIAAQgKAAgGgGQgGgGAAgJQAAgLAIgEQAIgHANABIAFAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAADgEAAQgGAAgEADQgEADAAAGQAAAFADADQAEADAGAAQAFAAADgCQADgDAAgHIAAgYQAAgGgDgDQgCgDgEAAIgGABIgFAFIgCACQgEAEgEAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgGAIgFQAHgEAMAAQAHAAAFACQAFACADAEQACADABAEIABANIAAAUIAAAGIACACIACABQAFABAAACQAAADgFADQgEADgGAAQgDAAgDgEg");
	this.shape_25.setTransform(-8.1,-10);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AANAwIgBgEIAAgCIAAgCIgBAAIgBABIgDACQgEADgDABIgIACQgMAAgIgJQgIgJAAgOQAAgRAJgJQAJgKAOAAIAEABIADACIABADQABADgFAAIgBAAIgCAAQgHAAgFAHQgEAEAAALQAAALAFAHQAEAHAIAAQAGAAAEgEQAEgDAAgIIAAgSIAAgeQAAgEgBgCQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgCgBQgEgBgBgCQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAHgDIAIgCIAFgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABIABADIAAAEIgBAoIABAbQAAAHABAAIAFACQAAAAABABQABAAAAAAQABABAAAAQAAABAAABQAAACgJADIgHACIgFABIgDgBg");
	this.shape_26.setTransform(-15.4,-11.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgLAvQgDgBAAgDQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIACgBIACgDIABgHIAAgFIAAgFIAAgHIAAgMQgBgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgEgBQgDgCAAgCIABgDIADgCIAKgDIAGgBIAEABIAAAEIAAAEIAAADIAAAQIgBARIABAJQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAIACABQABAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgLABIgNgBgAgHggQgDgDAAgDQAAgEADgCQADgDAEAAQAEAAADACQADADAAADQAAAEgEACQgDADgDAAQgEAAgDgCg");
	this.shape_27.setTransform(-21.5,-11.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgLAwQgCgBAAgEQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIADgBIACgGIABgMIAAgLIAAgMIAAgEIgBgWQgBgFgBAAIgEgCQgEgBAAgDIABgCIAGgDIAJgDIAGgBQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIABAEIAAAFIgBAvIABAWIACAHIADABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgMAAIgNAAg");
	this.shape_28.setTransform(-25.3,-11.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgXAZQgKgKAAgPQAAgOAKgKQAKgKAOAAQAPAAAJAJQAIAKABAPQAAAOgKAKQgKALgOAAQgOgBgJgJgAgMgTQgEAGAAAIQABAMAFAKQAGAIAGAAQAHAAAEgGQAEgFAAgJQAAgLgGgKQgFgJgHAAQgGABgFAFg");
	this.shape_29.setTransform(-30.7,-10);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAOAvQgDgBAAgDQAAgDAEgCIADgBQABgBABgEIAAgQIAAgJIAAgCQgBgBAAAAQAAAAgBgBQAAAAgBAAQgBAAgBAAIgPgBIgOABIgEABIgBACIAAAFIAAAFIABAQQAAAEABABIADABQAEACAAADQAAADgEABIgOABIgOgBQgDgBAAgDQAAgDADgCIADgBQACgBABgIIAAgcIAAgYQgBgKgBgBIgEgDQgDgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBABAAQACgBAMAAQAMAAADABQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQAAADgEABIgDACQgCABAAAEIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQACABAKAAIAFAAIAOgBIAFgBIABgBIAAgDIAAgDIAAgQIgCgEIgDgCQgEgBAAgDQAAgDADgBQADgBAMAAQALAAAEABQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAADgFABIgDACQgBABAAAJIgBAaIABAZQAAAKABABIAEADQADABABADQgBADgDABIgOABQgLAAgEgBg");
	this.shape_30.setTransform(-39.4,-11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.classicturkeydinnerfor8, new cjs.Rectangle(-46.4,-21.4,224.9,19.7), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// cta-rollover
	this.instance = new lib.seventeenrollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45.7,-9.8,91.5,19.6);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.WFM_Logo_White_RGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,0,0.223,0.223,0,0,0,175.2,174.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-39,-39,78,78), null);


// stage content:
(lib.mobileleaderboardnineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_19 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_198 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(19).call(this.frame_19).wait(179).call(this.frame_198).wait(3));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(201));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(201));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(192));

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(39.5,24.3,0.762,0.762,0,0,0,0.1,0.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({regX:0,regY:0,scaleX:0.05,scaleY:0.05},0).to({regX:0.1,regY:0.1,scaleX:0.82,scaleY:0.82,alpha:1},6,cjs.Ease.get(1)).to({scaleX:0.76,scaleY:0.76},7,cjs.Ease.get(1)).wait(179));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AwpIzIAAxkMAvKAAAIAARkg");
	mask.setTransform(195.3,22.4);

	// order-now
	this.instance_3 = new lib.seventeenordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(122.2,35);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(19).to({x:30.7},0).to({x:132.2,alpha:1},10,cjs.Ease.get(1)).to({x:122.2},8,cjs.Ease.get(1)).wait(164));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AyUIzIAAxkMAw1AAAIAARkg");
	mask_1.setTransform(195.3,22.4);

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(123.8,35.6);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(19).to({x:32.3},0).to({x:133.8,alpha:1},10,cjs.Ease.get(1)).to({x:123.8},8,cjs.Ease.get(1)).wait(164));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AyUIzIAAxkMAw1AAAIAARkg");
	mask_2.setTransform(195.3,22.4);

	// cta-rectangle
	this.instance_4 = new lib.seventeenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(123.8,35.6);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(19).to({x:32.3},0).to({x:133.8,alpha:1},10,cjs.Ease.get(1)).to({x:123.8},8,cjs.Ease.get(1)).wait(164));

	// herb-stuffing
	this.instance_5 = new lib.herbstuffing();
	this.instance_5.parent = this;
	this.instance_5.setTransform(137.5,15);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(117).to({y:24.5},0).to({alpha:1},10).wait(40).to({alpha:0},5).wait(29));

	// holiday-hosting-tips
	this.instance_6 = new lib.roastedturkey();
	this.instance_6.parent = this;
	this.instance_6.setTransform(149.8,24.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(67).to({alpha:1},10).wait(40).to({alpha:0},5).wait(79));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AyUIzIAAxkMAw1AAAIAARkg");
	mask_3.setTransform(195.3,22.4);

	// crowd-pleasing
	this.instance_7 = new lib.whatsinourclassicturkeydinner();
	this.instance_7.parent = this;
	this.instance_7.setTransform(164.3,23.6);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({x:-44.5,y:24.5},0).to({x:169.3,alpha:1},10,cjs.Ease.get(1)).to({x:164.3},8,cjs.Ease.get(1)).wait(40).to({alpha:0},5).wait(129));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("AyUIzIAAxkMAw1AAAIAARkg");
	mask_4.setTransform(195.3,22.4);

	// class-turkey-dinner-for-8
	this.instance_8 = new lib.classicturkeydinnerfor8();
	this.instance_8.parent = this;
	this.instance_8.setTransform(123.7,13.3);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(177).to({x:-84.3,y:23.6},0).to({x:130.7,alpha:1},10,cjs.Ease.get(1)).to({x:123.7},8,cjs.Ease.get(1)).wait(6));

	// kale-background
	this.instance_9 = new lib.kalebackground();
	this.instance_9.parent = this;
	this.instance_9.setTransform(162.3,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(201));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.1,16.8,338.5,70.3);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;